const projects = [
    {
      number: "01",
      title: "BiasharaIQ",
      description: "A bilingual bookkeeping and tax compliance app built for middle-sized businesses in Kenya. Auto-imports M-Pesa transactions via SMS, generates KRA eTIMS compliant invoices, tracks income, expenses and profit, and prepares tax reports for TOT, VAT and PAYE.",
      tech: ["React Native", "Expo", "Node.js", "Express", "Supabase", "PostgreSQL", "M-Pesa Daraja API", "KRA eTIMS API"],
      color: "#6366F1",
      github: "https://github.com/Bct3ch/biasharaiq",
      live: "https://expo.dev/accounts/cherono/projects/mobile/builds/6c067dc0-e45b-4564-824c-c4dafafc69d7",
    },
    {
      number: "02",
      title: "Project Name",
      description: "A short description of what this project does and what problem it solves.",
      tech: ["Next.js", "Tailwind CSS", "MongoDB"],
      color: "#06B6D4",
      github: "https://github.com",
      live: "https://example.com",
    },
    {
      number: "03",
      title: "Project Name",
      description: "A short description of what this project does and what problem it solves.",
      tech: ["Python", "Express", "REST API"],
      color: "#EC4899",
      github: "https://github.com",
      live: "https://example.com",
    },
    {
      number: "04",
      title: "Project Name",
      description: "A short description of what this project does and what problem it solves.",
      tech: ["React Native", "Node.js", "MongoDB"],
      color: "#6366F1",
      github: "https://github.com",
      live: "https://example.com",
    },
    {
      number: "05",
      title: "Project Name",
      description: "A short description of what this project does and what problem it solves.",
      tech: ["React", "Python", "PostgreSQL"],
      color: "#06B6D4",
      github: "https://github.com",
      live: "https://example.com",
    },
  ];